### ISSUE TITLE
no quartz oscillator gui on server

### ISSUE THREAD

**Issue by spyguy26** [elytra/InfraRedstone#5]
using minecraft 1.12.2
using infraredstone v1.01
and forge 1.12.2 - 14.23.4.2705
there appears to be no gui when I right click the quartz oscillator on the server yet it works fine on singleplayer
here is a link to the server's latest log https://gist.github.com/spyguy26/1a1e10bfecec61d76a7c4b12ec0034db

**Comment by LemmaEOF** [comment]
`java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/audio/ISound`
Huh. That's not something I've seen before. I'll take a look.

**Comment by LemmaEOF** [comment]
Looking into it more, it seems like an issue with the button class from Concrete. I'm gonna have to point this towards @falkreon so he can take a look at it.

**Comment by spyguy26** [comment]
Thank you kindly for the quick fix!

**Comment by LemmaEOF** [comment]
The last fix I did was really hacky, so I'm gonna redo it and make it not an awful hack
